flowchart LR
  Extract[Extract - OpenWeatherMap] --> Transform[Transform - pandas]
  Transform --> Load[Load - Postgres]
  Dag[Dag: weather_pipeline]
  Dag --> Extract

  Env[config/.env (local, secrets)] -.-> Dag
  Data[data/weather_data.json] --> Transform
  Postgres[/postgres-weather:5432/] <-- Load

  %% Notes
  Note1[Executa via docker compose up -d]
  Note2[Agende: a cada hora - cron: 0 */1 * * *]
